import 'package:hive_flutter/hive_flutter.dart';

class Player {
  Player({
    required this.id,
    required this.name,
    required this.position,
    required this.team,
    required this.number,
    required this.age,
    required this.height,
    required this.yc,
    required this.rc,
    required this.fouls,
    required this.shots,
    required this.goals,
    required this.passes,
    required this.tackles,
  });

  final int id;
  final String name;
  final String position;
  final String team;
  final String number;
  final String age;
  final String height;
  final String yc;
  final String rc;
  final String fouls;
  final String shots;
  final String goals;
  final String passes;
  final String tackles;
}

final emptyPlayer = Player(
  id: 0,
  name: '',
  position: '',
  team: '',
  number: '',
  age: '',
  height: '',
  yc: '',
  rc: '',
  fouls: '',
  shots: '',
  goals: '',
  passes: '',
  tackles: '',
);

class PlayerAdapter extends TypeAdapter<Player> {
  @override
  final typeId = 2;

  @override
  Player read(BinaryReader reader) {
    return Player(
      id: reader.read(),
      name: reader.read(),
      position: reader.read(),
      team: reader.read(),
      number: reader.read(),
      age: reader.read(),
      height: reader.read(),
      yc: reader.read(),
      rc: reader.read(),
      fouls: reader.read(),
      shots: reader.read(),
      goals: reader.read(),
      passes: reader.read(),
      tackles: reader.read(),
    );
  }

  @override
  void write(BinaryWriter writer, Player obj) {
    writer.write(obj.id);
    writer.write(obj.name);
    writer.write(obj.position);
    writer.write(obj.team);
    writer.write(obj.number);
    writer.write(obj.age);
    writer.write(obj.height);
    writer.write(obj.yc);
    writer.write(obj.rc);
    writer.write(obj.fouls);
    writer.write(obj.shots);
    writer.write(obj.goals);
    writer.write(obj.passes);
    writer.write(obj.tackles);
  }
}

List<Player> playersList = [
  Player(
    id: 1,
    name: 'Mohamed Salah',
    position: 'Forward',
    team: 'Liverpool',
    number: '11',
    age: '32',
    height: '175cm',
    yc: '10',
    rc: '0',
    fouls: '140',
    shots: '1014',
    goals: '175',
    passes: '8179',
    tackles: '138',
  ),
  Player(
    id: 2,
    name: 'Erling Haaland',
    position: 'Forward',
    team: 'Manchester City',
    number: '9',
    age: '24',
    height: '194cm',
    yc: '8',
    rc: '0',
    fouls: '63',
    shots: '325',
    goals: '79',
    passes: '1088',
    tackles: '15',
  ),
  Player(
    id: 3,
    name: 'Alexander Isak',
    position: 'Forward',
    team: 'Newcastle United',
    number: '14',
    age: '25',
    height: '192cm',
    yc: '5',
    rc: '0',
    fouls: '50',
    shots: '184',
    goals: '44',
    passes: '1181',
    tackles: '30',
  ),
  Player(
    id: 4,
    name: 'Bryan Mbeumo',
    position: 'Midfielder',
    team: 'Brentford',
    number: '19',
    age: '25',
    height: '173cm',
    yc: '13',
    rc: '0',
    fouls: '83',
    shots: '236',
    goals: '35',
    passes: '2786',
    tackles: '97',
  ),
  Player(
    id: 5,
    name: 'Cole Palmer',
    position: 'Midfielder',
    team: 'Chelsea',
    number: '20',
    age: '22',
    height: '189cm',
    yc: '11',
    rc: '0',
    fouls: '36',
    shots: '194',
    goals: '35',
    passes: '2267',
    tackles: '45',
  ),
  Player(
    id: 6,
    name: 'Chris Wood',
    position: 'Forward',
    team: 'Nottingham Forest',
    number: '11',
    age: '33',
    height: '191cm',
    yc: '6',
    rc: '0',
    fouls: '194',
    shots: '386',
    goals: '81',
    passes: '3666',
    tackles: '61',
  ),
  Player(
    id: 7,
    name: 'Matheus Cunha',
    position: 'Forward',
    team: 'Wolverhampton Wanderers',
    number: '10',
    age: '25',
    height: '183cm',
    yc: '12',
    rc: '0',
    fouls: '75',
    shots: '153',
    goals: '24',
    passes: '1547',
    tackles: '63',
  ),
  Player(
    id: 8,
    name: 'Yoane Wissa',
    position: 'Midfielder',
    team: 'Brentford',
    number: '11',
    age: '28',
    height: '176cm',
    yc: '12',
    rc: '0',
    fouls: '80',
    shots: '168',
    goals: '36',
    passes: '1333',
    tackles: '61',
  ),
  Player(
    id: 9,
    name: 'Nicolas Jackson',
    position: 'Forward',
    team: 'Chelsea',
    number: '15',
    age: '23',
    height: '186cm',
    yc: '14',
    rc: '0',
    fouls: '46',
    shots: '130',
    goals: '23',
    passes: '909',
    tackles: '34',
  ),
  Player(
    id: 10,
    name: 'Liam Delap',
    position: 'Forward',
    team: 'Ipswich Town',
    number: '19',
    age: '21',
    height: '186cm',
    yc: '6',
    rc: '0',
    fouls: '41',
    shots: '35',
    goals: '8',
    passes: '175',
    tackles: '7',
  ),
  Player(
    id: 11,
    name: 'Luis Díaz',
    position: 'Forward',
    team: 'Liverpool',
    number: '7',
    age: '27',
    height: '178cm',
    yc: '6',
    rc: '0',
    fouls: '114',
    shots: '196',
    goals: '24',
    passes: '2274',
    tackles: '75',
  ),
  Player(
    id: 12,
    name: 'Raúl Jiménez',
    position: 'Forward',
    team: 'Fulham',
    number: '7',
    age: '33',
    height: '190cm',
    yc: '17',
    rc: '3',
    fouls: '183',
    shots: '421',
    goals: '55',
    passes: '3914',
    tackles: '127',
  ),
  Player(
    id: 13,
    name: 'James Maddison',
    position: 'Midfielder',
    team: 'Tottenham Hotspur',
    number: '10',
    age: '28',
    height: '175cm',
    yc: '33',
    rc: '1',
    fouls: '171',
    shots: '479',
    goals: '55',
    passes: '7951',
    tackles: '281',
  ),
  Player(
    id: 14,
    name: 'Aston Villa',
    position: 'Forward',
    team: 'Aston Villa',
    number: '11',
    age: '29',
    height: '180cm',
    yc: '17',
    rc: '1',
    fouls: '148',
    shots: '419',
    goals: '67',
    passes: '2820',
    tackles: '82',
  ),
  Player(
    id: 15,
    name: 'Jhon Durán',
    position: 'Forward',
    team: 'Aston Villa',
    number: '9',
    age: '21',
    height: '185cm',
    yc: '9',
    rc: '1',
    fouls: '34',
    shots: '56',
    goals: '12',
    passes: '287',
    tackles: '16',
  ),
  Player(
    id: 16,
    name: 'Kai Havertz',
    position: 'Forward',
    team: 'Arsenal',
    number: '29',
    age: '25',
    height: '193cm',
    yc: '24',
    rc: '0',
    fouls: '206',
    shots: '268',
    goals: '39',
    passes: '3634',
    tackles: '116',
  ),
  Player(
    id: 17,
    name: 'Brennan Johnson',
    position: 'Forward',
    team: 'Tottenham Hotspur',
    number: '22',
    age: '23',
    height: '186cm',
    yc: '12',
    rc: '0',
    fouls: '74',
    shots: '152',
    goals: '20',
    passes: '1530',
    tackles: '95',
  ),
  Player(
    id: 18,
    name: 'Dominic Solanke',
    position: 'Forward',
    team: 'Tottenham Hotspur',
    number: '19',
    age: '27',
    height: '187cm',
    yc: '6',
    rc: '0',
    fouls: '139',
    shots: '293',
    goals: '36',
    passes: '2044',
    tackles: '76',
  ),
  Player(
    id: 19,
    name: 'Jørgen Strand Larsen',
    position: 'Forward',
    team: 'Wolverhampton Wanderers',
    number: '9',
    age: '24',
    height: '193cm',
    yc: '2',
    rc: '0',
    fouls: '25',
    shots: '31',
    goals: '7',
    passes: '250',
    tackles: '6',
  ),
  Player(
    id: 20,
    name: 'Cody Gakpo',
    position: 'Forward',
    team: 'Liverpool',
    number: '18',
    age: '25',
    height: '193cm',
    yc: '5',
    rc: '0',
    fouls: '64',
    shots: '137',
    goals: '21',
    passes: '1195',
    tackles: '70',
  ),
  Player(
    id: 21,
    name: 'Mark Flekken',
    position: 'Goalkeeper',
    team: 'Brentford',
    number: '1',
    age: '31',
    height: '195cm',
    yc: '4',
    rc: '0',
    fouls: '2',
    shots: '0',
    goals: '0',
    passes: '2327',
    tackles: '0',
  ),
  Player(
    id: 22,
    name: 'Arijanet Muric',
    position: 'Goalkeeper',
    team: 'Ipswich Town',
    number: '1',
    age: '26',
    height: '198cm',
    yc: '1',
    rc: '0',
    fouls: '0',
    shots: '0',
    goals: '0',
    passes: '1023',
    tackles: '0',
  ),
  Player(
    id: 23,
    name: 'Mads Hermansen',
    position: 'Goalkeeper',
    team: 'Leicester City',
    number: '30',
    age: '24',
    height: '187cm',
    yc: '0',
    rc: '0',
    fouls: '0',
    shots: '0',
    goals: '0',
    passes: '506',
    tackles: '0',
  ),
  Player(
    id: 24,
    name: 'Robert Sánchez',
    position: 'Goalkeeper',
    team: 'Chelsea',
    number: '1',
    age: '27',
    height: '197cm',
    yc: '14',
    rc: '1',
    fouls: '6',
    shots: '0',
    goals: '0',
    passes: '4116',
    tackles: '0',
  ),
  Player(
    id: 25,
    name: 'Jordan Pickford',
    position: 'Goalkeeper',
    team: 'Everton',
    number: '1',
    age: '30',
    height: '185cm',
    yc: '21',
    rc: '0',
    fouls: '6',
    shots: '0',
    goals: '0',
    passes: '9786',
    tackles: '0',
  ),
  Player(
    id: 26,
    name: 'Bernd Leno',
    position: 'Goalkeeper',
    team: 'Fulham',
    number: '1',
    age: '32',
    height: '189cm',
    yc: '10',
    rc: '1',
    fouls: '3',
    shots: '0',
    goals: '0',
    passes: '6123',
    tackles: '0',
  ),
  Player(
    id: 27,
    name: 'Matz Sels',
    position: 'Goalkeeper',
    team: 'Nottingham Forest',
    number: '26',
    age: '32',
    height: 'cm',
    yc: '3',
    rc: '0',
    fouls: '0',
    shots: '0',
    goals: '0',
    passes: '808',
    tackles: '0',
  ),
  Player(
    id: 28,
    name: 'Dean Henderson',
    position: 'Goalkeeper',
    team: 'Crystal Palace',
    number: '1',
    age: '27',
    height: '188cm',
    yc: '11',
    rc: '0',
    fouls: '1',
    shots: '0',
    goals: '0',
    passes: '2772',
    tackles: '0',
  ),
  Player(
    id: 29,
    name: 'Aaron Ramsdale',
    position: 'Goalkeeper',
    team: 'Southampton',
    number: '30',
    age: '26',
    height: '190cm',
    yc: '4',
    rc: '0',
    fouls: '1',
    shots: '0',
    goals: '0',
    passes: '4570',
    tackles: '0',
  ),
  Player(
    id: 30,
    name: 'Nick Pope',
    position: 'Goalkeeper',
    team: 'Newcastle United',
    number: '22',
    age: '32',
    height: '191cm',
    yc: '12',
    rc: '1',
    fouls: '4',
    shots: '0',
    goals: '0',
    passes: '5184',
    tackles: '0',
  ),
  // Player(
  //   id: 31,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 32,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 33,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 34,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 35,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 36,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 37,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 38,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 39,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
  // Player(
  //   id: 40,
  //   name: '',
  //   position: '',
  //   team: '',
  //   number: '',
  //   age: '',
  //   height: 'cm',
  //   yc: '',
  //   rc: '',
  //   fouls: '',
  //   shots: '',
  //   goals: '',
  //   passes: '',
  //   tackles: '',
  // ),
];
